# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:                                   # Everyone can access the access token URL.
                pattern: ^/oauth/v2/token
                security: false
        api:
            pattern: ^/                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false
        main:
            anonymous: ~

    access_control:
                  # require ROLE_ADMIN for /admin*
               - { path: ^/api/medico, roles: ROLE_MEDICO }
               - { path: ^/api/paciente, roles: ROLE_PACIENTE}
               - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
            # activate different ways to authenticate
    role_hierarchy:
            ROLE_MEDICO:       ROLE_PACIENTE
            ROLE_SUPER_ADMIN:   ROLE_MEDICO
            ROLE_SUPER_ADMIN:  ROLE_ADMIN
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
